#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Awesome Title
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Hernán Valdés
  pic: 1
  position: Lead Developer
  social:
    - title: github
      url: https://github.com/hfvaldesg
    
- name: Javier Carrasco
  pic: 2
  position: Lead Developer 2
  social:
    - title: github
      url: https://github.com/javiercmh
    - title: linkedin
      url: https://www.linkedin.com/in/ja-vier/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/hfvaldesg/time-manager

# Build settings
markdown: kramdown
permalink: pretty
